- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
    - name: copying mongo.repo
      ansible.builtin.copy:
        src: /home/ec2-user/mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: installing mongodb
      ansible.builtin.yum:
        name: mongodb-org -y 
        state: present
    - name: starting and enabling mongodb
      ansible.builtin.systemd_service:
        state: started
        name: mongod
        enabled: true        
    - name: Replace localhost to public
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: Restart mongod service
      ansible.builtin.service:
        name: mongod
        state: restarted
    
    