- name: installing payment
  hosts: payment
  become: yes
  tasks:
    - name: installing python 
      ansible.builtin.ym:
        name: "{{item}}"
        state: present
      loop:
        - python3
        - gcc
        - python3-devel
    - name: checking roboshop user exists or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true
    - name: printing the output
      ansible.builtin.debug:
        msg: "{{output}}"    
    - name: adding user
      ansible.builtin.user:
        name: roboshop
      when:  output.rc !=0 
    - name: checking /app directory exists or not
      ansible.builtin.stat: 
        path: /app
      register: output
    - name: printing output
      ansible.builtin.debug:
        msg: "{{output}}"    
    - name: creating directory
      ansible.builtin.file:
        path: /app
        state: directory
      when: output.stat.exists == false  
    - name: Downloading the code to /app directory
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
        dest: /tmp       
    - name: unzip to app directory
      ansible.builtin.unarchive:
        src: /tmp/payment-v3.zip
        dest: /app
        remote_src: yes
    - name: Change the working directory to app and install dependencies
      ansible.builtin.shell: pip3 install -r requirements.txt
      args:
        chdir: /app
    - name: copy payment.service
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service
    - name: daemon-reload payment.systemd_service
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: starting and enabling payment
      ansible.builtin.systemd_service:
        state: started
        name: payment
        enabled: true      
