- name: installing rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
    - name: copying rabbitmq.repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: installing rabbitmq-server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: present
    - name: starting and enabling rabbitmq
      ansible.builtin.systemd_service:
        state: started
        name: rabbitmq-server
        enabled: true        